poroPics:
    Mitchel: https://i.imgur.com/qGWNJI6.jpg
    Dorian: https://i.imgur.com/eY7722M.jpg
    Rupert: https://i.imgur.com/YHEneSA.jpg
    Pip: https://i.imgur.com/IRz71Sq.png
    Mort: https://i.imgur.com/Ir8OP15.png
    Munch: https://i.imgur.com/VrENQFY.png
    Maddie: https://i.imgur.com/Xz1Hm06.jpg
    Varo: https://i.imgur.com/GFs2KN3.jpg
    Arco: https://i.imgur.com/e2LeJ6Z.jpg
    Shakira: https://i.imgur.com/mdM9Q08.jpg
poroIntros:
    - "Soft lil thing for you!\n"
    - "Made of magic, love, and a lil bit of sugar.\n"
    - "Fresh one right out the oven!\n"
    - "This one seems to like you, aww.\n"
    - "Poros make the best pets!\n"
    - "Snaks! Does anyone have any snaks for the lil guy!?\n"
    - "Ever seen one this fluffy?\n"
    - "You can never lose a poro, they're just real good at hide&seek.\n"
    - "Even in the coldest climates, poros never stop smiling.\n"
    - "I think this one will do just fine.\n"